### ISSUE TITLE
Easy way to change keyboard shortcut key?

### ISSUE THREAD

**Issue by gnacho** [ivoarch/gnome-shell-TilixDropdown#1]
Is there any chance to get it by extension configuration? What would be the combination of two keys?

**Comment by ivoarch** [comment]
Hi. 
for the moment, you can change the combination only by editing the scheme file .

Edit  **schemas/org.gnome.shell.extensions.terminix-dropdown.gschema.xml** schema file with your custom shortcut keys .

Example shortcut combination of two keys 

1) <kbd>Alt</kbd> key + <kbd>t</kbd>
``` xml
<default><![CDATA[['<Alt>t']]]></default>
```
2) <kbd>Ctrl</kbd> key + <kbd>t</kbd>
``` xml
<default><![CDATA[['<Ctrl>t']]]></default>
```
3) <kbd>Super</kbd> key + <kbd>t</kbd>
``` xml
<default><![CDATA[['<Super>t']]]></default>
```
Then compile with `glib-compile-schemas .`  inside the directory . 
Restart the extension or Gnome Shell .

**Comment by gnacho** [comment]
Many thanks!! :)

**Comment by gnacho** [comment]
Amazing! The last update already fix this issue and let the user choose any combination by UI. Many thanks for this amazing work!!!!!
