### ISSUE TITLE
What about Wayland support?

### ISSUE THREAD

**Issue by zefkerr** [ivoarch/gnome-shell-TilixDropdown#14]
Hi! Thank you very much for your great work! But what about Wayland support?
When I try to open Tilix with your extension in quake mode using GNOME Wayland I see an error massage about quake mode not supported under Wayland. Now I use GNOME 3.28, but when I previously used GNOME 3.26, I was perfectly able to use your extension under Wayland and I was happy with everything.
But why now I can not use your extension with Wayland anymore?

Arch Linux, GNOME 3.28

**Comment by ivoarch** [comment]
Quake mode is no longer supported in Wayland see this issue https://github.com/gnunn1/tilix/issues/1314

**Comment by Kerrung** [comment]
But I was completely satisfied with how it worked with Wayland. Can you create a separate branch with Wayland support? But I was completely satisfied with how it worked with Wayland. Maybe you'll create a separate branch with Wayland support for those who are happy with Wayland?

**Comment by zefkerr** [comment]
*ivoarch, But I was completely satisfied with how it worked with Wayland. Can you create a separate branch with Wayland support? But I was completely satisfied with how it worked with Wayland. Maybe you'll create a separate branch with Wayland support for those who are happy with Wayland?
