### ISSUE TITLE
Tilix dropdown mode disabled on wayland

### ISSUE THREAD

**Issue by m-a-r-c-o** [ivoarch/gnome-shell-TilixDropdown#16]
Unfortunately the dropdown mode was removed for tilix running under wayland. See:

https://github.com/gnunn1/tilix/issues/1314

I solved the problem on my System (Fedora 28 under wayland) by adding the following env setup to the tilix call in the extension code:

```
function _startTilix() {
    try {
        Main.Util.trySpawnCommandLine('env GDK_BACKEND=x11 tilix --quake');
    } catch(err) {
        Main.notify("Couldn't start tilix, is it installed?");
    }
}
```

This should also work if running under x11.

@ivoarch would you consider this change for inclusion?

**Comment by ivoarch** [comment]
Fixed Thanks!!

**Comment by m-a-r-c-o** [comment]
Great. Thanks!
