### ISSUE TITLE
Terminix has been renamed to Tilix due to trademark issue

### ISSUE THREAD

**Issue by terencode** [ivoarch/gnome-shell-TilixDropdown#2]
More information at https://github.com/gnunn1/tilix/issues/815

**Comment by ivoarch** [comment]
Hi,
I'm will try to apply the new changes with the name very soon .

**Comment by terencode** [comment]
Hey, 
Thanks for fixing it ;).

**Comment by ivoarch** [comment]
For the moment I've updated the extension only on github . In the next stable release of Tilix I'll upload the new extension in Gnome Shell Extensions Page .

**Comment by terencode** [comment]
I noticed so I'm using it from source.

**Comment by ivoarch** [comment]
Ok, can you confirm that everything works ?
Thanks!!

**Comment by terencode** [comment]
Everything is working fine, except some 'random' `Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1c06fa2 (Tilix: Par)
` when starting it.

**Comment by ivoarch** [comment]
Thanks!
I think that this message has nothing to do with the extension . Have you tried to start `tilix --quake` from the command line and see if the message appears again ?

**Comment by terencode** [comment]
No problem, you were right it happens with tilix --quake too and it's about toggling it too fast.
