### ISSUE TITLE
Create new release with fix for Gnome 3.32

### ISSUE THREAD

**Issue by taasan** [ivoarch/gnome-shell-TilixDropdown#22]
Commit 345e427f3fd94089116977fa1c266d1312d35f85 fixes crash on Gnome >= 3.32. The fix has not yet been released.

**Comment by ivoarch** [comment]
Hi, 
I create new release with Gnome 3.32 support ! Here https://github.com/ivoarch/gnome-shell-TilixDropdown/releases/tag/7 
I also added the release in GNOME Shell extension website maybe we need do wait some time to see it .

**Comment by ivoarch** [comment]
Thanks!!
