### ISSUE TITLE
"Couldn't start Tilix, is it installed?"

### ISSUE THREAD

**Issue by steelstring94** [ivoarch/gnome-shell-TilixDropdown#4]
The title of this issue is the error message I am getting when I hit F10 after installing Tilix.  It seems a very strange error message to me because, if it weren't installed, how would I even get this message?

I have tried restarting Gnome shell as per the instructions; no dice.

**Comment by ivoarch** [comment]
Hi,
You have tilix installed in your system?
If the message appears also with the tilix installed try to turn on/off the extension from gnome-tweak-tool.

**Comment by steelstring94** [comment]
Hi,
Yes, it's installed.  Turning it off and on again doesn't help.  Still 
the same message.

**Comment by ivoarch** [comment]
Which version of GNOME Shell you use ?
The command output of `type tilix` ?

**Comment by steelstring94** [comment]
It was a fresh install of the latest ISO of Ubuntu Gnome from ubuntu.com.
I've just switched over to KDE as I found Ubuntu Gnome to be extremely
buggy, though.

**Comment by ivoarch** [comment]
I tried the latest Ubuntu GNOME 17.04 and the extension works correctly !
Possibly something happens with the installation of your tilix package . I am going to close this issue because I really don't see any problem with the extension .

**Comment by mstankie** [comment]
Hi! I am facing exactly the same issue after upgrade to 19.04. My tilix was working correctly in Quake mode, but now when I hit F10 or click the icon, I see same message.
I had a fresh install of 18.10 before (installed end of March).
Tilix is installed -I can start it from command line.
Turning it off and on again doesn't help in my case as well.
GNOME Shell 3.32.0
`type tilix` says: `tilix jest /usr/bin/tilix`

**Comment by ivoarch** [comment]
Hi try to install the extension from github.   View #18
