### ISSUE TITLE
How to change the default size of dropdown ternimal?

### ISSUE THREAD

**Issue by gaunthan** [ivoarch/gnome-shell-TilixDropdown#5]
Hi. Could I change the default size of tilix dropdown?

**Comment by ivoarch** [comment]
Hi,
you can change default size from the **_hamburger menu - Preferences - Quake - Size_** .
Also please note that the extesnsion just launch tilix mode [quake](https://github.com/gnunn1/tilix/wiki/Quake-Mode) . All available options and settings do not depend on this extension . If you have any configuration problem with tilix, it is best to open issue here https://github.com/gnunn1/tilix/issues .

**Comment by gaunthan** [comment]
That's cool. Thanks! :-D
