### ISSUE TITLE
installation?

### ISSUE THREAD

**Issue by sigmamale1980** [ivoarch/gnome-shell-TilixDropdown#6]
Hi, tried installing from both gnome ext. & git repo but refuses to start keep getting
"Couldn`t start tilix, is it installed?"

any ideas?

thx in adv.

**Comment by ivoarch** [comment]
Hi,
You have tilix installed in your system?

**Comment by sigmamale1980** [comment]
yes .. but wont start like i mentioned .. strange!

BTW .. OS is Debian testing

**Comment by ivoarch** [comment]
GNOME version and distribution ?

also `type tilix` in terminal?

**Comment by sigmamale1980** [comment]
yes typed "tilix" & still nothing.

Gnome Version 3.22.2

**Comment by ivoarch** [comment]
I want to know the path where tilix is installed on your Debian.
If the extension does not start is because not find tilix binary on your $PATH . Please paste de output of `type tilix` from your terminal.  Have you tried to start tilix terminal from GNOME application menu?

**Comment by sigmamale1980** [comment]
path is: ~/.local/share/gnome-shell/extensions/TilixDropdown@ivkuzev@gmail.com
well it says command not found for type tilix .. and yes, will not open on gnome-apps menu

**Comment by ivoarch** [comment]
Try to install tilix again from other source . Because currently you does not have tilix installed .

**Comment by sigmamale1980** [comment]
will do thx
