### ISSUE TITLE
Can't open Tilix

### ISSUE THREAD

**Issue by ghost** [ivoarch/gnome-shell-TilixDropdown#9]
Whenever I try to use the dropdown with my own shortcut, I get a notification saying "Couldn't start tilix, is it installed?" even though I have it installed and I could change the keyboard shortcut.

I am using Ubuntu 17.10 GNOME.

**Comment by sferich888** [comment]
If you do ctrl+r (tilix --quake) - in GNOME, does that do what you want?
https://github.com/ivoarch/gnome-shell-TilixDropdown/blob/master/extension.js#L41-L47 

It might be that tilix is not in your path an thus why this is happening.
